### ISSUE TITLE
Some promQL issue found

### ISSUE THREAD

**Issue by Nexucis** [promlabs/lezer-promql#1]
Maybe that's a false positive, and it's on my side I didn't used properly the lezer grammar. But so far I didn't find where was the issue.

* first issue using `rate`

![image](https://user-images.githubusercontent.com/4548045/87699542-4d59b280-c795-11ea-94a1-ccf1f073b105.png)

* second with `topk`, when it's not correct one in two. It's not necessary big issue since otherall the query is not ok

![image](https://user-images.githubusercontent.com/4548045/87699743-9b6eb600-c795-11ea-91f2-570a940aaae1.png)

It's just super weird. I was more expected that everything was hightlight in red excepting the first line

**Comment by Nexucis** [comment]
cc @juliusv : doesn't seem you are watching the project. But in case you are already aware of this issue, then I'm sorry for the spam

**Comment by juliusv** [comment]
@Nexucis Indeed, I should probably watch the repo :)

I'm not sure there's a problem with the grammar here - both examples are incorrect PromQL expressions (the first one is missing quotes around the label value), and indicate an error approximately where the syntax error is. Though for me, omitting the quotes on the label value even gives me a better error indication (starting at the `500`, not just the brace afterwards):

![expression](https://user-images.githubusercontent.com/538008/87845670-a6c2fe00-c8c9-11ea-8b77-7f78df3ce8a2.png)

**Comment by Nexucis** [comment]
ah yeah my bad for the firt one.

But for the second one; I'm still thinking there is something weird. Because yes I'm agree that's not a correct promQL query so it's normal that the editor is yelling.

But then it should yell for others as well like this one:

![image](https://user-images.githubusercontent.com/4548045/87848971-58bbf380-c8e5-11ea-9d8f-55fb38d0ca5c.png)

Or this one to keep the `topk` query:

![image](https://user-images.githubusercontent.com/4548045/87848998-87d26500-c8e5-11ea-956f-b5e8704e645d.png)

**Comment by juliusv** [comment]
Hm yeah, that's weird. Not sure why it doesn't indicate an error token anywhere for just two full expressions following each other. Will have to analyze that more closely.

**Comment by Nexucis** [comment]
maybe it doesn't really matter.

I was looking at the linter feature in CMN, and we could do the same things that what has been done in Prometheus itself : which is looping over the tree returned by the parser and add more check.

Note that the linter feature is not completed I supposed since it doesn't show the error message. Maybe I should open an issue on CMN side ....

**Comment by Nexucis** [comment]
with the linter built in the codemirror-promql, it's ok if the grammar is a bit partial in term of possible error
