### ISSUE TITLE
Cannot parse metrics beginning with `inf`

### ISSUE THREAD

**Issue by faceair** [promlabs/lezer-promql#33]
![image](https://user-images.githubusercontent.com/3659110/116002584-060a2780-a62d-11eb-96fa-295a3c413a80.png)
It looks like the syntax parsing for metric names starting with `inf` will determine that it is the `Inf` in mathematics.

**Comment by Nexucis** [comment]
same issue with `nan`

I believe it is coming from [here](https://github.com/promlabs/lezer-promql/blob/57d8bb11d3bd1cd1134e262ee6225d2cc1372e48/src/promql.grammar#L313-L314)

**Comment by juliusv** [comment]
Yes, this problem is mentioned in the first sentences of https://lezer.codemirror.net/docs/guide/#token-specialization. I've already tried to make this work in various ways for an hour or two now, but so far I haven't been smart enough yet, and I'm then always running into some other problems.

**Comment by Nexucis** [comment]
I tried too on my side, and I was wondering if in the Identifier we could put the `Inf` and `NaN` in a negative expression. Like that it would say an identifier is everything except `Inf` or except `NaN`
